# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171229_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 16, 53, 25, 494636, tzinfo=utc)),
        ),
    ]
