# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171229_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='keywords',
            new_name='tags',
        ),
    ]
