# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171229_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='pub_datee',
        ),
    ]
