# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 22:35
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.DateTimeField(default=datetime.datetime(2017, 11, 26, 14, 35, 1, 570187))),
                ('strategy_ror', models.FloatField(default=0.0)),
                ('play_rand_date', models.DateTimeField(default=datetime.datetime(2017, 11, 26, 14, 35, 1, 570187))),
                ('companies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('company_1', models.FloatField(default=0.0)),
                ('company_2', models.FloatField(default=0.0)),
                ('company_3', models.FloatField(default=0.0)),
                ('company_4', models.FloatField(default=0.0)),
                ('company_5', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('ticker', models.CharField(max_length=10)),
                ('price', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Sp100',
            fields=[
                ('ticker', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('security', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('isin', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='gameinput',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hindsight1.Sp100'),
        ),
    ]
