# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 23:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindsight1', '0002_auto_20171126_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playrecord',
            name='play_rand_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 26, 15, 46, 27, 308284)),
        ),
        migrations.AlterField(
            model_name='playrecord',
            name='play_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 26, 15, 46, 27, 308284)),
        ),
    ]
