# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 02:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('hindsight1', '0006_auto_20171127_1826'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='playrecord',
            managers=[
                ('playrecord', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='playrecord',
            name='play_rand_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 28, 18, 24, 2, 757424)),
        ),
        migrations.AlterField(
            model_name='playrecord',
            name='play_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 28, 18, 24, 2, 757424)),
        ),
    ]
