# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 02:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindsight1', '0008_auto_20171128_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playrecord',
            name='play_rand_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 28, 18, 39, 55, 972823)),
        ),
        migrations.AlterField(
            model_name='playrecord',
            name='play_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 28, 18, 39, 55, 972823)),
        ),
    ]
