# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 01:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindsight1', '0013_auto_20171203_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='playrecord',
            name='played',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playrecord',
            name='play_rand_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 17, 14, 43, 559529)),
        ),
        migrations.AlterField(
            model_name='playrecord',
            name='play_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 17, 14, 43, 559529)),
        ),
    ]
