# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 01:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindsight1', '0016_auto_20171203_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playrecord',
            name='played',
        ),
        migrations.AlterField(
            model_name='playrecord',
            name='play_rand_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 17, 21, 8, 194135)),
        ),
        migrations.AlterField(
            model_name='playrecord',
            name='play_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 17, 21, 8, 194135)),
        ),
    ]
