# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 03:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindsight1', '0033_auto_20171216_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playrecord',
            name='play_rand_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 19, 42, 35, 424191)),
        ),
        migrations.AlterField(
            model_name='playrecord',
            name='play_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 19, 42, 35, 424191)),
        ),
    ]
