# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindsight1', '0035_auto_20171220_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playrecord',
            name='play_rand_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 19, 40, 3, 741696)),
        ),
        migrations.AlterField(
            model_name='playrecord',
            name='play_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 19, 40, 3, 741696)),
        ),
    ]
