# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 03:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindsight1', '0057_auto_20171229_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinput',
            name='ticker',
        ),
        migrations.AlterModelManagers(
            name='playrecord',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='playrecord',
            name='play_rand_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='GameInput',
        ),
    ]
